---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "app.name" $ }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion }}
    helm.sh/chart: {{ include "app.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
type: Opaque
data:
{{- range .Values.config.providers }}
  {{- if eq .type "github" }}
  SGC_GITHUB_TOKEN: {{ required "github token must be set" .token | b64enc }}
  {{- else if eq .type "gitlab" }}
  SGC_GITLAB_TOKEN: {{ required "gitlab token must be set" .token | b64enc }}
  {{- end }}
{{- end }}
  SGC_SLACK_TOKEN: {{ required "slack token must be set" .Values.config.slack.token | b64enc }}
  SGC_SLACK_SIGNING_SECRET: {{ required "slack signing secret must be set" (index .Values.config.slack "signing-secret") | b64enc }}
