---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}-config
  labels:
    app.kubernetes.io/name: {{ include "app.name" $ }}
    app.kubernetes.io/version: {{ $.Chart.AppVersion }}
    helm.sh/chart: {{ include "app.chart" $ }}
    app.kubernetes.io/instance: {{ $.Release.Name }}
    app.kubernetes.io/managed-by: {{ $.Release.Service }}
type: Opaque
data:
  SGC_GITHUB_URL: {{ .Values.config.github.url | b64enc }}
  SGC_GITHUB_TOKEN: {{ .Values.config.github.token | b64enc }}
  SGC_GITHUB_ORGS: {{ .Values.config.github.orgs | b64enc }}
  SGC_GITLAB_URL: {{ .Values.config.gitlab.url | b64enc }}
  SGC_GITLAB_TOKEN: {{ .Values.config.gitlab.token | b64enc }}
  SGC_GITLAB_GROUPS: {{ .Values.config.gitlab.groups | b64enc }}
  SGC_LOG_FORMAT: {{ .Values.config.log.format | b64enc }}
  SGC_LOG_LEVEL: {{ .Values.config.log.level | b64enc }}
  SGC_SLACK_TOKEN: {{ .Values.config.slack.token | b64enc }}
  SGC_SLACK_SIGNING_SECRET: {{ index .Values.config.slack "signing-secret" | b64enc }}
