---
kind: pipeline
name: release

steps:
  - name: build
    image: alpine/helm
    commands:
      - apk add --no-cache make git bash
      - make release

  - name: release
    image: appleboy/drone-git-push
    settings:
      remote_name: origin
      branch: gh-pages
      local_ref: gh-pages

trigger:
  branch:
    - test
  event:
    - push
    - tag

# ---
# kind: pipeline
# name: test

# steps:
#   - name: lint
#     image: alpine/helm
#     commands:
#       - apk add --no-cache make
#       - make lint

# trigger:
#   event:
#     - push
#     - pull_request
#     - tag


# depends_on:
#   - test

# ---
# kind: signature
# hmac: 66957bea3ad6ccee81ce0b6025d13a29545462c3f018cadf79d234d800fa7c19

# ...
