---
apiVersion: v1
name: gitlab-ci-pipelines-exporter
version: 0.0.3
appVersion: 0.4.2
description: Prometheus / OpenMetrics exporter for GitLab CI pipelines insights
home: https://github.com/mvisonneau/gitlab-ci-pipelines-exporter
sources:
  - https://github.com/mvisonneau/helm-charts/tree/main/charts/gitlab-ci-pipelines-exporter
maintainers:
  - name: mvisonneau
    email: maxime.visonneau@gmail.com
dependencies:
  - name: redis
    version: 11.0.7
    repository: https://charts.bitnami.com/bitnami
    condition: redis.enabled
