{{- if .Values.tls.enabled -}}
---
apiVersion: v1
kind: Secret
metadata:
  name: {{ template "app.fullname" . }}-tls
  labels:
    {{- include "app.labels" . | nindent 4 }}
type: Opaque
data:
  ca.crt: {{ toYaml .Values.tls.ca | b64enc }}
  server.crt: {{ toYaml .Values.tls.cert | b64enc }}
  server.key: {{ toYaml .Values.tls.key | b64enc }}
{{- end }}