---
on:
  pull_request:
  push:

jobs:
  helm:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: actions/setup-go@v4
        with:
          go-version: '1.20.4'

      - name: Set up Helm
        uses: azure/setup-helm@v3
        with:
          version: v3.12.0

      - name: Run chart-testing (lint)
        run: make lint

      # - name: Create kind cluster
      #   uses: helm/kind-action@v1.2.0
      #   if: steps.list-changed.outputs.changed == 'true'

      # - name: Test installing the charts
      #   run: make test

  kubeconform:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        # When changing versions here, check that the version exists at: https://github.com/instrumenta/kubernetes-json-schema
        k8s:
          - '1.23.17'
          - '1.24.14'
          - '1.25.10'
          - '1.26.5'
          - '1.27.2'

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Add dependency chart repos
        run: |
          helm repo add stable https://charts.helm.sh/stable

      - name: Run kubeval
        env:
          KUBERNETES_VERSION: ${{ matrix.k8s }}
        run: .github/kubeval.sh
